version: '3.7'

services:
  db_test:
    image: postgres:15.1-alpine
    container_name: db_app_test
    command: -p 1221
    expose:
      - 1221
    env_file: .env-test

  redis_test:
    image: redis:7
    container_name: redis_app_test
    command: --port 5370
    expose:
      - 5370

  app_test:
    build:
      context: .
      dockerfile: Dockerfile-test

    env_file: .env-test

    container_name: fastapi_app_test

    command: ['/restaurant_fastapi_test/docker/test.sh']


    depends_on:
      - db_test
      - redis_test

    restart: 'no'
