version: '3.7'

services:
  db:
    image: postgres:15.1-alpine
    container_name: db_app
    env_file: .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379


  app:
    build:
      context: .
      dockerfile: Dockerfile

    env_file: .env-non-dev

    container_name: fastapi_app

    command: ['/restaurant_fastapi/docker/app.sh']

    ports:
      - 8000:8000


    depends_on:
      - db
      - redis
    

  rabbit:
    image: rabbitmq:latest
    container_name: rabbit
    env_file: .env-non-dev

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    env_file: .env-non-dev
    volumes:
      - .:/app
    container_name: worker_celery
    command: ['/restaurant_fastapi/docker/celery.sh', 'worker']
    depends_on:
      - rabbit

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    volumes:
      - .:/app
    env_file: .env-non-dev
    container_name: celery
    command: ['/restaurant_fastapi/docker/celery.sh', 'admin']
    depends_on:
      - rabbit
      - worker

volumes:
  postgres_data:
    driver: local
