version: '3.7'  

services:
  db_test:
    image: postgres:15.1-alpine
    container_name: db_app_test
    env_file: .env-test

  app_test:
    build:
      context: .
      dockerfile: Dockerfile-test

    env_file: .env-test

    container_name: fastapi_app_test

    command: ['/restaurant_fastapi_test/docker/test.sh']

    ports:
      - 8000:8000

    depends_on:
      - db_test