"""add autoincrement

Revision ID: fdf114517118
Revises: 1de2ba4a8928
Create Date: 2023-07-22 13:12:18.498597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf114517118'
down_revision = '1de2ba4a8928'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
