"""add relotionship

Revision ID: a66f0d3eee11
Revises: 2df3253a28fd
Create Date: 2023-08-12 00:56:48.890484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66f0d3eee11'
down_revision = '2df3253a28fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
